// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-JzoH6m9-nQccff8ZKsFLX2vm8IxpiTI',
    appId: '1:57932149579:web:3cec7acb87a20cee7b6ece',
    messagingSenderId: '57932149579',
    projectId: 'projectpulse-1faf3',
    authDomain: 'projectpulse-1faf3.firebaseapp.com',
    storageBucket: 'projectpulse-1faf3.firebasestorage.app',
    measurementId: 'G-M22DWZQX1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr3tp7NRW3GweYalAxPauyRApFstbEjIU',
    appId: '1:57932149579:android:18c099a5d473a5a37b6ece',
    messagingSenderId: '57932149579',
    projectId: 'projectpulse-1faf3',
    storageBucket: 'projectpulse-1faf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnuUvERQtK5MZJAm3Xe9sBjoY6RskD14o',
    appId: '1:57932149579:ios:5682c2d2a29285bc7b6ece',
    messagingSenderId: '57932149579',
    projectId: 'projectpulse-1faf3',
    storageBucket: 'projectpulse-1faf3.firebasestorage.app',
    iosBundleId: 'com.example.freelanceFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnuUvERQtK5MZJAm3Xe9sBjoY6RskD14o',
    appId: '1:57932149579:ios:5682c2d2a29285bc7b6ece',
    messagingSenderId: '57932149579',
    projectId: 'projectpulse-1faf3',
    storageBucket: 'projectpulse-1faf3.firebasestorage.app',
    iosBundleId: 'com.example.freelanceFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-JzoH6m9-nQccff8ZKsFLX2vm8IxpiTI',
    appId: '1:57932149579:web:40e9930144b930a37b6ece',
    messagingSenderId: '57932149579',
    projectId: 'projectpulse-1faf3',
    authDomain: 'projectpulse-1faf3.firebaseapp.com',
    storageBucket: 'projectpulse-1faf3.firebasestorage.app',
    measurementId: 'G-VHB3S6TXNZ',
  );
}
